version: '3.6'

services:
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: sivdev
      POSTGRES_USER: sivpack
      POSTGRES_PASSWORD: sivpack_dev
    ports:
      - "9432:5432"
  redis:
    image: redis:4.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  web:
    build:
      context: .
    command: ["gunicorn", "app:app", "-b", "0.0.0.0:5000", "--reload", "--timeout",  "100000"]
    depends_on:
      - db
    volumes:
      - .:/home/web/
      - ./.pdbrc.py:/home/sivpack/.pdbrc.py
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    environment: &env_vars
      FLASK_APP: /home/web/app/__init__.py
      DATABASE_URI: postgresql://sivpack:sivpack_dev@db:5432/sivdev
      REDIS_URI: redis://redis:6379

  worker:
    build:
      context: .
    command: ["python", "start_async_worker.py"]
    depends_on:
      - db
    volumes:
      - .:/home/web/
      - ./.pdbrc.py:/home/sivpack/.pdbrc.py
    stdin_open: true
    tty: true
    environment: *env_vars
  # rq-dash:
  #   build:
  #     context: ./rq-dashboard/
  #   environment:
  #     RQ_DASHBOARD_REDIS_URL: redis://redis:6379
  #   depends_on:
  #     - redis
  #   ports:
  #     - "9181:9181"
  #   command: ["rq-dashboard"]
