version: '3'

services:
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: sivdev
      POSTGRES_USER: sivpack
      POSTGRES_PASSWORD: sivpack_dev
    ports:
      - "9432:5432"
  web:
    build:
      context: .
    image: app_web
    command: ["gunicorn", "app:app", "-b", "0.0.0.0:5000", "--reload", "--timeout",  "100000"]
    depends_on:
      - db
    volumes:
      - .:/home/web/
      - ./.pdbrc.py:/home/sivpack/.pdbrc.py
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    environment:
      FLASK_APP: /home/web/app/__init__.py
      DATABASE_URI: postgresql://sivpack:sivpack_dev@db:5432/sivdev
