"""

Revision ID: 55f830eb6483
Revises: ffb0672283af
Create Date: 2019-03-23 17:01:06.377150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f830eb6483'
down_revision = 'ffb0672283af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'failed')
    # ### end Alembic commands ###
